<?xml version="1.0" encoding="UTF-8"?>
<!-- insert xml declaration -->



<!-- new xml with doctype with subset -->
<!DOCTYPE Student [
    <!ELEMENT Student (name?, age, class, fees)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT class (#PCDATA)>
    <!ELEMENT fees (#PCDATA)>
]>
<Student>
    <name>Ali</name>
    <age>23</age>
    <class>10</class>
    <fees>8000</fees>
</Student>
